openapi: 3.0.0
info:
  title: Event Management API
  description: An API developed for our WBD project that serves our project.
  version: 1.0.0
servers:
  - url: http://localhost:4000
    description:  Main (production) Backend server
  - url: http://localhost:3000
    description:  Main (production) Frontend server
tags:
  - name: Event Management System


# -------------------------------------------------------------------------

paths:
  /booking:
    get:
      summary: Lists all the bookings done till now 
      tags: [Bookings]
      responses:
        "200":
          description: The list of all bookings.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bookings'
    post:
      summary: Adds a new booking record.
      tags: [Bookings]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bookings'
      responses: 
        '200':
          description: Created
        '400':
          description: Error
  
  /booking/{bookingID}:
    get:
      summary: Returns information of a booking by ID.
      tags: [Bookings]
      parameters:
        - name: bookingID
          in: path
          required: true
          description: Autogenerated Booking ID by MongoDB
          schema:
            type : string
      responses: 
        '200':
          description: OK
        '400':
          description: Record does not exist
        '500':
          description: Error

    delete:
      summary: Deletes a booking by ID.
      tags: [Bookings]
      parameters:
        - name: bookingID
          in: path
          required: true
          description: Autogenerated Booking ID by MongoDB
          schema:
            type : string
      responses: 
        '200':
          description: Deleted
        '400':
          description: Record does not exist
        '500':
          description: Error
          
    patch:
      summary: Update a booking information
      tags: [Bookings]
      parameters:
        - name: bookingID
          in: path
          required: true
          description: Autogenerated Booking ID by MongoDB
          schema:
            type : string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bookings'
      responses:
        '200':
          description: Booking Data Updated
          schema:
            $ref: "#/components/schemas/Bookings"
        '400':
          description: Error

#-------------------------------------------------------------------
components:
  schemas:
    Bookings:
      type: object
      required:
        - name
        - date
        - day
        - time
        - venues_name
        - silver
        - platinium
        - price
        - total_price
        - banner_image_url
        - grade

      properties:
        id:
          type: string
          description: The auto-generated id of the booking.
        name:
          type: string
          description: The name of the show.
        date:
          type: number
          description: Date of the show
        day:
          type: string
          description: Day of the show
        time:
          type: string
          description: Time of the show
        venues_name:
          type: string
          description: Name of the venue
        silver:
          type: array
          items:
            type: string
          description: Description of silver seats booked
        platinium:
          type: array
          items:
            type: string
          description: Description of platinium seats booked
        price:
          type: number
          description: Price of the seats
        total_price:
          type: number
          description: Total price 
        banner_image_url:
          type: string
          description: URL of the banner image
        grade:
          type: string
          description: Rating of the show  
      
      example:
        name: "Sunburn Music Festival"
        date: 7
        day: "Friday"
        time: "07:00 PM"
        venues_name: "PVR: Pacific, Subhash Nagar, Delhi"
        silver: ["A6","A7","A8"]
        platinium: ["D8"]
        price: 336
        total_price: 364
        language: "English"
        banner_image_url: "https://media.resources.festicket.com/image/372x525/center/middle/filt..."
        grade: "ua"
