name: Main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
      - name: Install mocha
        run: |
          npm i redis jsonwebtoken chai chai-http express mongoose cookie-parser csurf fs file-stream-rotator swagger-ui-express yamljs morgan multer helmet cors dotenv
          npm i mocha -g
      - name: Run Test
        working-directory: ./backend
        run: node test
